Repository Team-Lecue/Lecue-Server, pull requests merged in 2024-01, with the labels that each got.

#5 [CHORE] CI/CD 세팅
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/org/sopt/lequuServer/global/common/config/AWSConfig.java
  src/main/resources/application.yml
  src/main/resources/bootstrap.yml
Labels: 🧹Chore, 🚀Deploy, 동섭🔥, 🔥 Pull Request

#12 [FEAT] 초기 Entity 설계 + 폴더 구조 세팅
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  src/main/java/org/sopt/lequuServer/domain/postit/model/Postit.java
  src/main/java/org/sopt/lequuServer/domain/rollingpaper/model/RollingPaper.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/PostedSticker.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/Sticker.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/StickerCategory.java
  src/main/java/org/sopt/lequuServer/domain/user/model/User.java
  src/main/java/org/sopt/lequuServer/global/common/exception/CustomException.java
  src/main/java/org/sopt/lequuServer/global/common/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/lequuServer/global/common/model/BaseTimeEntity.java
  src/main/java/org/sopt/lequuServer/global/config/AWSConfig.java
  src/main/java/org/sopt/lequuServer/global/config/JpaAuditingConfig.java
  src/main/java/org/sopt/lequuServer/global/config/WebConfig.java
  src/main/resources/application.yml
Labels: 🧹Chore, ☁️Database, ✨Feat, 동섭🔥, 🔥 Pull Request

#17 [FEAT] 사진 업로드를 위한 S3 + Presigned URL 구현
  build.gradle
  src/main/java/org/sopt/lequuServer/domain/rollingpaper/model/RollingPaper.java
  src/main/java/org/sopt/lequuServer/domain/user/model/User.java
  src/main/java/org/sopt/lequuServer/global/common/dto/ApiResponse.java
  src/main/java/org/sopt/lequuServer/global/common/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/lequuServer/global/common/exception/enums/SuccessType.java
  src/main/java/org/sopt/lequuServer/global/config/AWSConfig.java
  src/main/java/org/sopt/lequuServer/global/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/ErrorType.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
  src/main/java/org/sopt/lequuServer/global/exception/model/CustomException.java
  src/main/java/org/sopt/lequuServer/global/s3/controller/S3Controller.java
  src/main/java/org/sopt/lequuServer/global/s3/dto/PreSignedUrlResponse.java
  src/main/java/org/sopt/lequuServer/global/s3/enums/ImageFolderName.java
  src/main/java/org/sopt/lequuServer/global/s3/service/S3Service.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestController.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestCreateImageRequest.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestCreateRequest.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestJpaRepository.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestService.java
  src/main/resources/application.yml
Labels: 🪄API, ✨Feat, 동섭🔥, 🔥 Pull Request

#20 [CHORE] 서비스 용어집에 따른 네이밍 변경
  src/main/java/org/sopt/lequuServer/domain/book/model/Book.java
  src/main/java/org/sopt/lequuServer/domain/note/model/Note.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/PostedSticker.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/Sticker.java
  src/main/java/org/sopt/lequuServer/domain/user/model/User.java
  src/main/java/org/sopt/lequuServer/global/s3/controller/S3Controller.java
  src/main/java/org/sopt/lequuServer/global/s3/enums/ImageFolderName.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestController.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestJpaRepository.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestService.java
Labels: 🧹Chore, ☁️Database, 동섭🔥, 예진❄️

#21 [DEPLOY] Update CD.yml
  .github/workflows/CD.yml
Labels: 🧹Chore

#24 🚀 [DEPLOY] 로컬, 배포 서버 환경 분리
  .gitignore
  Dockerfile
  src/main/java/org/sopt/lequuServer/global/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 🚀Deploy, 동섭🔥, 🔥 Pull Request

#25 [REFACTOR] 토큰 관리 관련 리팩토링 진행
  src/main/java/org/sopt/lequuServer/domain/user/dto/response/UserLoginResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/user/model/User.java
  src/main/java/org/sopt/lequuServer/domain/user/service/UserService.java
  src/main/java/org/sopt/lequuServer/global/auth/fegin/kakao/KakaoLoginService.java
  src/main/java/org/sopt/lequuServer/global/auth/jwt/JwtProvider.java
  src/main/java/org/sopt/lequuServer/global/auth/redis/RefreshToken.java
  src/main/java/org/sopt/lequuServer/global/auth/redis/TokenRepository.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/ErrorType.java
Labels: ☁️Database, 동섭🔥, 🔥 Pull Request, 🔨Refactor

#28 [FEAT] 스티커팩 목록 불러오기 API 구현
  src/main/java/org/sopt/lequuServer/domain/book/model/Book.java
  src/main/java/org/sopt/lequuServer/domain/book/repository/BookJpaRepository.java
  src/main/java/org/sopt/lequuServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/request/SocialLoginRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MemberLoginResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/model/Member.java
  src/main/java/org/sopt/lequuServer/domain/member/model/SocialPlatform.java
  src/main/java/org/sopt/lequuServer/domain/member/repository/MemberJpaRepository.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/model/Note.java
  src/main/java/org/sopt/lequuServer/domain/sticker/controller/StickerController.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerPackResponse.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerResponse.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/PostedSticker.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/Sticker.java
  src/main/java/org/sopt/lequuServer/domain/sticker/repository/StickerJpaRepository.java
  src/main/java/org/sopt/lequuServer/domain/sticker/service/StickerService.java
  src/main/java/org/sopt/lequuServer/domain/user/dto/response/UserLoginResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/user/repository/UserJpaRepository.java
  src/main/java/org/sopt/lequuServer/global/auth/fegin/kakao/KakaoLoginService.java
  src/main/java/org/sopt/lequuServer/global/auth/jwt/JwtProvider.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/ErrorType.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
  src/main/java/org/sopt/lequuServer/global/s3/controller/S3Controller.java
  src/main/java/org/sopt/lequuServer/global/s3/service/S3Service.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestController.java
  src/main/resources/application-local.yml
Labels: 🪄API, 🧹Chore, ☁️Database, ✨Feat, 동섭🔥, 🔥 Pull Request

#30 [FEAT] 스플래시 조회 기능 구현
  src/main/java/org/sopt/lequuServer/domain/book/repository/BookRepository.java
  src/main/java/org/sopt/lequuServer/domain/common/controller/CommonController.java
  src/main/java/org/sopt/lequuServer/domain/common/dto/response/SplashDto.java
  src/main/java/org/sopt/lequuServer/domain/common/facade/CommonFacade.java
  src/main/java/org/sopt/lequuServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/repository/NoteRepository.java
  src/main/java/org/sopt/lequuServer/domain/note/service/NoteService.java
  src/main/java/org/sopt/lequuServer/domain/sticker/repository/StickerRepository.java
  src/main/java/org/sopt/lequuServer/domain/sticker/service/StickerService.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
Labels: 🪄API, ☁️Database, ✨Feat, 동휘⚡️, 🔥 Pull Request

#33 [CHORE] Swagger 설정 추가
  build.gradle
  src/main/java/org/sopt/lequuServer/global/config/SecurityConfig.java
  src/main/java/org/sopt/lequuServer/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 🧹Chore, ✨Feat, 동휘⚡️

#31 [FEAT] 레큐북 생성 api 구현
  src/main/java/org/sopt/lequuServer/domain/book/controller/BookController.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/request/BookCreateRequest.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookCreateResponse.java
  src/main/java/org/sopt/lequuServer/domain/book/facade/BookFacade.java
  src/main/java/org/sopt/lequuServer/domain/book/service/BookService.java
  src/main/java/org/sopt/lequuServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/global/auth/jwt/JwtProvider.java
  src/main/java/org/sopt/lequuServer/global/auth/redis/RefreshToken.java
  src/main/java/org/sopt/lequuServer/global/auth/security/JwtAuthenticationFilter.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
Labels: 🪄API, ✨Feat, 예진❄️, 🔥 Pull Request

#36 [DOCS] README.md 초안 작성
  .gitmessage.txt
  README.md
Labels: 동섭🔥, 📃Docs

#34 [FEAT] 홈 API 구현
  src/main/java/org/sopt/lequuServer/InitDb.java
  src/main/java/org/sopt/lequuServer/domain/book/controller/BookController.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookCreateResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/book/facade/BookFacade.java
  src/main/java/org/sopt/lequuServer/domain/book/model/Book.java
  src/main/java/org/sopt/lequuServer/domain/book/repository/BookRepository.java
  src/main/java/org/sopt/lequuServer/domain/book/service/BookService.java
  src/main/java/org/sopt/lequuServer/domain/common/controller/CommonController.java
  src/main/java/org/sopt/lequuServer/domain/common/dto/response/PopularBookResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/common/facade/CommonFacade.java
  src/main/java/org/sopt/lequuServer/global/config/SecurityConfig.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
Labels: 🪄API, 🧹Chore, ✨Feat, 동휘⚡️, 🔥 Pull Request

#37 [FEAT] 레큐노트 생성 API 구현
  src/main/java/org/sopt/lequuServer/domain/book/facade/BookFacade.java
  src/main/java/org/sopt/lequuServer/domain/book/repository/BookRepository.java
  src/main/java/org/sopt/lequuServer/domain/book/service/BookService.java
  src/main/java/org/sopt/lequuServer/domain/common/facade/CommonFacade.java
  src/main/java/org/sopt/lequuServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/controller/NoteController.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/request/NoteCreateDto.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/response/NoteResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/note/facade/NoteFacade.java
  src/main/java/org/sopt/lequuServer/domain/note/service/NoteService.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
Labels: 🪄API, ✨Feat, 동휘⚡️, 🔥 Pull Request, 🔨Refactor

#39 [FEAT] 스티커 부착하기 API 구현
  src/main/java/org/sopt/lequuServer/InitDb.java
  src/main/java/org/sopt/lequuServer/domain/book/controller/BookController.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/request/BookCreateRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/book/facade/BookFacade.java
  src/main/java/org/sopt/lequuServer/domain/book/model/Book.java
  src/main/java/org/sopt/lequuServer/domain/book/repository/BookRepository.java
  src/main/java/org/sopt/lequuServer/domain/book/service/BookService.java
  src/main/java/org/sopt/lequuServer/domain/common/facade/CommonFacade.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/facade/NoteFacade.java
  src/main/java/org/sopt/lequuServer/domain/note/service/NoteService.java
  src/main/java/org/sopt/lequuServer/domain/sticker/controller/StickerController.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/request/StickerPostRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerPackResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerPostResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/facade/StickerFacade.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/PostedSticker.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/Sticker.java
  src/main/java/org/sopt/lequuServer/domain/sticker/repository/PostedStickerRepository.java
  src/main/java/org/sopt/lequuServer/domain/sticker/repository/StickerRepository.java
  src/main/java/org/sopt/lequuServer/domain/sticker/service/StickerService.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/ErrorType.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
  src/main/java/org/sopt/lequuServer/global/s3/controller/S3Controller.java
  src/main/java/org/sopt/lequuServer/global/s3/enums/ImageFolderName.java
Labels: 🪄API, ✨Feat, 동섭🔥, 🔥 Pull Request, 🔨Refactor

#40 [FEAT] 유저 닉네임 설정 API 구현
  src/main/java/org/sopt/lequuServer/InitDb.java
  src/main/java/org/sopt/lequuServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/request/MemberNicknameRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MemberNicknameResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/model/Member.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
Labels: 🪄API, ✨Feat, 동섭🔥, 🔥 Pull Request

#41 [FEAT] 레큐북 삭제 API 구현
  .github/workflows/CD.yml
  src/main/java/org/sopt/lequuServer/InitDb.java
  src/main/java/org/sopt/lequuServer/domain/book/controller/BookController.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/request/BookCreateRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/book/facade/BookFacade.java
  src/main/java/org/sopt/lequuServer/domain/common/controller/CommonController.java
  src/main/java/org/sopt/lequuServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/request/MemberNicknameRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MemberNicknameResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/model/Member.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/controller/NoteController.java
  src/main/java/org/sopt/lequuServer/domain/note/facade/NoteFacade.java
  src/main/java/org/sopt/lequuServer/domain/sticker/controller/StickerController.java
  src/main/java/org/sopt/lequuServer/domain/sticker/model/StickerCategory.java
  src/main/java/org/sopt/lequuServer/domain/sticker/repository/StickerRepository.java
  src/main/java/org/sopt/lequuServer/global/config/WebConfig.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
Labels: 🪄API, ✨Feat, 예진❄️, 🔥 Pull Request

#43 [FEAT] 마이페이지 조회 API 구현
  src/main/java/org/sopt/lequuServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookListResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageNoteResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/request/NoteCreateDto.java
  src/main/java/org/sopt/lequuServer/domain/note/facade/NoteFacade.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
Labels: 🪄API, ✨Feat, 예진❄️, 🔥 Pull Request

#47 [FIX] 기능명세서 보며 빠진 부분 보충
  src/main/java/org/sopt/lequuServer/InitDb.java
  src/main/java/org/sopt/lequuServer/domain/book/controller/BookController.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/request/BookCreateRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/book/repository/BookRepository.java
  src/main/java/org/sopt/lequuServer/domain/common/facade/CommonFacade.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/request/MemberNicknameRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageNoteResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/controller/NoteController.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/request/NoteCreateDto.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/response/NoteDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/note/facade/NoteFacade.java
  src/main/java/org/sopt/lequuServer/domain/sticker/controller/StickerController.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
Labels: ✨Feat, 동섭🔥, 🔧Modify, 🔥 Pull Request

#49 [FEAT] Sentry 기능 연동
  build.gradle
  src/main/java/org/sopt/lequuServer/domain/common/controller/CommonController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🧹Chore, 🚀Deploy, ✨Feat, 동휘⚡️, 🔥 Pull Request

#51 [CHORE] Swagger 설정
  src/main/java/org/sopt/lequuServer/domain/book/controller/BookController.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/request/BookCreateRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookCreateResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/common/controller/CommonController.java
  src/main/java/org/sopt/lequuServer/domain/common/dto/response/PopularBookResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/common/dto/response/SplashDto.java
  src/main/java/org/sopt/lequuServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/request/MemberNicknameRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/request/SocialLoginRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MemberLoginResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MemberNicknameResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookListResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageNoteResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/note/controller/NoteController.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/request/NoteCreateDto.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/response/NoteCreateResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/response/NoteDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/controller/StickerController.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/request/StickerPostRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/PostedStickerDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerPackResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerPostResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerResponseDto.java
  src/main/java/org/sopt/lequuServer/global/auth/jwt/TokenDto.java
  src/main/java/org/sopt/lequuServer/global/s3/controller/S3Controller.java
  src/main/java/org/sopt/lequuServer/global/s3/dto/PreSignedUrlResponse.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestController.java
Labels: 🧹Chore, 예진❄️, 🔥 Pull Request

#54 [FIX] 마이페이지 수정
  src/main/java/org/sopt/lequuServer/domain/book/controller/BookController.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookCreateResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/common/controller/CommonController.java
  src/main/java/org/sopt/lequuServer/domain/common/dto/response/PopularBookResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/common/dto/response/SplashDto.java
  src/main/java/org/sopt/lequuServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookListResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageNoteListResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageNoteResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/controller/NoteController.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/response/NoteDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/controller/StickerController.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/PostedStickerDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerPostResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerResponseDto.java
  src/main/java/org/sopt/lequuServer/global/config/SwaggerConfig.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestController.java
Labels: 예진❄️, 🔧Modify, 🔥 Pull Request

#62 [REFACTOR] background 형식 통일
  src/main/java/org/sopt/lequuServer/InitDb.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/request/BookCreateRequestDto.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/book/model/Book.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageNoteListResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/request/NoteCreateDto.java
  src/main/java/org/sopt/lequuServer/domain/note/dto/response/NoteDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/note/model/Note.java
Labels: 🪄API, 동휘⚡️, 🔧Modify, 🔥 Pull Request, 🔨Refactor

#61 [FIX] 디스코드 알림 수정사항 반영
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  src/main/java/org/sopt/lequuServer/global/common/logging/LoggingMessage.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/discord-business-appender.xml
  src/main/resources/discord-error-appender.xml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-local.xml
Labels: 🧹Chore, 동섭🔥, 🔧Modify, 🔥 Pull Request

#66 [FEAT] 닉네임 중복 에러로그 출력
  src/main/java/org/sopt/lequuServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/ErrorType.java
Labels: ✨Feat, 동휘⚡️, 🔧Modify, 🔥 Pull Request

#63 [FEAT] 비속어 필터링 설정
  build.gradle
  src/main/java/org/sopt/lequuServer/domain/book/facade/BookFacade.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/facade/NoteFacade.java
  src/main/java/org/sopt/lequuServer/global/BadWordFilterService.java
  src/main/resources/BadWord.txt
Labels: ✨Feat, 예진❄️, 🔥 Pull Request

#67 [FIX] 윤한이형 피드백 반영
  src/main/java/org/sopt/lequuServer/domain/book/controller/BookApi.java
  src/main/java/org/sopt/lequuServer/domain/book/controller/BookController.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/book/facade/BookFacade.java
  src/main/java/org/sopt/lequuServer/domain/book/model/Book.java
  src/main/java/org/sopt/lequuServer/domain/common/controller/CommonApi.java
  src/main/java/org/sopt/lequuServer/domain/common/controller/CommonController.java
  src/main/java/org/sopt/lequuServer/domain/member/controller/MemberApi.java
  src/main/java/org/sopt/lequuServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBookResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageBooksResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageNoteResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MypageNotesResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/note/controller/NoteApi.java
  src/main/java/org/sopt/lequuServer/domain/note/controller/NoteController.java
  src/main/java/org/sopt/lequuServer/domain/note/facade/NoteFacade.java
  src/main/java/org/sopt/lequuServer/domain/sticker/controller/StickerApi.java
  src/main/java/org/sopt/lequuServer/domain/sticker/controller/StickerController.java
  src/main/java/org/sopt/lequuServer/domain/sticker/dto/response/StickerPackResponseDto.java
  src/main/java/org/sopt/lequuServer/global/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/lequuServer/global/exception/enums/SuccessType.java
  src/main/java/org/sopt/lequuServer/global/s3/controller/S3Api.java
  src/main/java/org/sopt/lequuServer/global/s3/controller/S3Controller.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestController.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestCreateImageRequest.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestCreateRequest.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestJpaRepository.java
  src/main/java/org/sopt/lequuServer/global/s3/test/TestService.java
Labels: 동섭🔥, 🔧Modify, 🔥 Pull Request, 🔨Refactor

#69 [FEAT] 욕설 필터링 업그레이드
  src/main/java/org/sopt/lequuServer/domain/book/facade/BookFacade.java
  src/main/java/org/sopt/lequuServer/domain/log/model/BadWordLog.java
  src/main/java/org/sopt/lequuServer/domain/log/repository/BadWordLogRepository.java
  src/main/java/org/sopt/lequuServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/lequuServer/domain/note/facade/NoteFacade.java
  src/main/java/org/sopt/lequuServer/global/BadWordFilterService.java
Labels: ☁️Database, ✨Feat, 동휘⚡️, 🔧Modify, 🔥 Pull Request

#70 [CHORE] 데모데이 더미 데이터 추가 및 욕설 필터링 추가
  src/main/java/org/sopt/lequuServer/InitDb.java
  src/main/java/org/sopt/lequuServer/domain/book/dto/response/BookDetailResponseDto.java
  src/main/java/org/sopt/lequuServer/domain/member/dto/response/MemberNicknameResponseDto.java
  src/main/resources/BadWord.txt
Labels: 🧹Chore, 동섭🔥, 동휘⚡️, 🔥 Pull Request
